Add a deadline option to the spider
SURFnet/apie pull request #12
Opened 2024-09-25 10:09 UTC by mdemare

- **Set charset to utf-8 in report**
- **Clean up code**
- **Added deadline for spider**

2024-09-25 13:59 UTC, joodie requested changes

2024-09-25 13:59 UTC, joodie commented on src/nl/jomco/apie/spider.clj
> +(defn wrap-timeout [f timeout-at]
Ah dat was me niet eens opgevallen.

Ik wil hier gewoon een maximaal aantal (milli)seconden opgeven, niet een timestamp waarop het verloopt.

2024-09-25 13:59 UTC, joodie commented on src/nl/jomco/apie/spider.clj
> +(defn wrap-timeout [f timeout-at]
Sorry voor het heen-en-weer gepingpong

2024-09-25 14:36 UTC, mdemare commented on src/nl/jomco/apie/spider.clj
> +(defn wrap-timeout [f timeout start]
goed punt

2024-09-25 15:11 UTC, joodie approved these changes

2024-10-16 08:00 UTC, joodie approved these changes

2024-10-16 19:17 UTC, merged